language: java
before_install:
  - git clone --branch=mvn https://github.com/MagpieBridge/CryptoLSPDemo.git mvnRepo
  - cd mvnRepo
  - cp -r repository $HOME/.m2/repository
  - cd ..
  - git clone --branch=lsp https://github.com/linghuiluo/FlowDroid.git FlowDroid
  - cd FlowDroid
  - mvn install -DskipTests
  - cd ..
  - git clone --branch=develop https://github.com/MagpieBridge/MagpieBridge.git MagpieBridge
  - cd MagpieBridge
  - mvn install -DskipTests
  - cd ..
script:   
  - mvn install 
