language: java
before_install:
  - pwd
  - git clone --branch=mvn https://github.com/MagpieBridge/CryptoLSPDemo.git  $HOME/travis/build/MagpieBridge/mvnRepo
  - cd $HOME/travis/build/MagpieBridge/mvnRepo
  - cp -r repository $HOME/.m2/repository
  - git clone --branch=lsp https://github.com/linghuiluo/FlowDroid.git $HOME/travis/build/MagpieBridge/FlowDroid
  - cd $HOME/travis/build/MagpieBridge/FlowDroid
  - mvn install -DskipTests
  - git clone --branch=develop https://github.com/MagpieBridge/MagpieBridge.git $HOME/travis/build/MagpieBridge/MagpieBridge
  - cd $HOME/travis/build/MagpieBridge/MagpieBridge
  - mvn install -DskipTests
  - pwd
  - cd $HOME/travis/build/MagpieBridge/CryptoLSPDemo
script:   
  - mvn install 
