language: java
before_install:
  - git clone --branch=websockets https://github.com/MagpieBridge/lsp4j $HOME/build/MagpieBridge/lsp4j
  - cd $HOME/build/MagpieBridge/lsp4j
  - gradle build -x test
  - gradle install -Dmaven.repo.local=$HOME/.m2/repository
    
  - git clone --branch=master https://github.com/MagpieBridge/CryptoAnalysis.git $HOME/build/MagpieBridge/CryptoAnalysis
  - cd $HOME/build/MagpieBridge/CryptoAnalysis/CryptoAnalysis
  - mvn install -DskipTests
  
  - git clone --branch=lsp https://github.com/linghuiluo/FlowDroid.git $HOME/build/MagpieBridge/FlowDroid
  - cd $HOME/build/MagpieBridge/FlowDroid
  - mvn install -DskipTests
  
  - git clone --branch=develop https://github.com/MagpieBridge/MagpieBridge.git $HOME/build/MagpieBridge/MagpieBridge
  - cd $HOME/build/MagpieBridge/MagpieBridge
  - mvn install -DskipTests
  
  - cd $HOME/build/MagpieBridge/CryptoLSPDemo
script:   
  - mvn install -DskipTests
