language: java
before_install:
  - git clone --branch=lsp https://github.com/linghuiluo/FlowDroid.git $HOME/build/MagpieBridge/FlowDroid
  - cd $HOME/build/MagpieBridge/FlowDroid
  - mvn install -DskipTests
  
  - cd $HOME/build/MagpieBridge/CryptoLSPDemo
script:   
  - mvn install -DskipTests
